### ISSUE TITLE
[버그 제보] 로그인 유지 기능이 안되요

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/E2E1-KernelEngine#117]
> **Describe the bug**
로그인 유지 기능이 작동하지 않는 것 같습니다.

<br>

>  **To Reproduce**
_Steps to reproduce the behavior_

1. 로그인 유지 체크 없이 로그인
2. 리프레시 토큰 만료일이 1일 후로 쿠키에 저장됨
3. 로그아웃 이후 쿠키에 데이터 없어짐을 확인
4. 로그인 유지 체크 후 로그인
4. 리프레시 토큰 만료일이 1일 후로 이전과 같은 Expire date 속성을 가짐.

<br>

> **Expected behavior**
두개의 리프레시 토큰이 expire date 속성값이 달라야 할 것 같습니다!

<br>

**Comment by anso33** [comment]
감사합니다 확인했습니다!
