### ISSUE TITLE
[버그 제보] 회원탈퇴가 안됩니다.

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/E2E1-KernelEngine#119]
![image](https://github.com/Kernel360/E2E1-KernelEngine/assets/59242594/c09af221-4d65-4755-b119-7368333c5401)

마이페이지 > 회원탈퇴 시 알 수 없는 페이지로 이동합니다!!

**Comment by anso33** [comment]
감사합니다. 해결했습니다!!
