### ISSUE TITLE
[버그 제보] 관리자페이지 에러 발생합니다.

### ISSUE THREAD

**Issue by HyunJunSon** [Kernel360/E2E1-KernelEngine#122]
**버그 설명**
관리자페이지 들어가 지지 않습니다.
**발생 경위**
관리자페이지 버튼 누르면 아래와 같이 에러 페이지 등장합니다.
**정상 동작**
관리자페이지 보고싶습니다.
**스크린샷**
(가능하시다면, 버그 발생과 관련된 스크린샷을 남겨주시면 빠른 개선에 도움이 됩니다)
![image](https://github.com/Kernel360/E2E1-KernelEngine/assets/91066575/452ff302-21ba-48b8-8bf5-29f5e3f9b300)
![image](https://github.com/Kernel360/E2E1-KernelEngine/assets/91066575/d14758f8-0bdd-4871-a48d-58c2eda51cf6)

**추가 사항**
(추가적으로 전달하고 싶은 사항이 있다면 남겨주세요)

**Comment by anso33** [comment]
감사합니다 버그 수정했습니다!
