### ISSUE TITLE
[버그 제보] 최초 검색 이후에는 정렬기준 설정이 안되요

### ISSUE THREAD

**Issue by linglong67** [Kernel360/E2E1-KernelEngine#124]
> **Describe the bug**
_A clear and concise description of what the bug is._
최초 검색 이후에는 정렬 기준이 사라져요

<br>

>  **To Reproduce**
_Steps to reproduce the behavior_

홈에서 1회 이상 검색한 경우 발생

<br>

> **Expected behavior**
_A clear and concise description of what you expected to happen._
정렬 기준은 검색할 때마다 필요하면 적용할 수 있으면 좋을 것 같아요
지금은 다시 홈 화면 눌러야 처음처럼 나와서 정렬 조건 추가할 수 있어요

<br>

> **Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://github.com/Kernel360/E2E1-KernelEngine/assets/88479739/6dca7938-30e0-40d7-9bdb-08a8a7864815)

<br>

> **Desktop 환경:**

<br>

> **Smartphone 환경 구성:**

<br>

> **Additional context**
_Add any other context about the problem here._
수고하셨습니다~~!

**Comment by anso33** [comment]
감사합니다 해결했습니다!
