### ISSUE TITLE
[버그 제보] 검색시 정렬 셀렉트 박스가 사라짐

### ISSUE THREAD

**Issue by aqrms** [Kernel360/E2E1-KernelEngine#125]
> **Describe the bug**
_A clear and concise description of what the bug is._

홈에서 검색어를 입력하기 전에는 '정렬 기준' 셀렉트 박스가 보이나
검색어를 입력하면 사라집니다 

> **Expected behavior**
_A clear and concise description of what you expected to happen._
<br>
검색이후 정렬 기준 셀렉트 박스를 통해 검색결과를 정렬

> **Screenshots**
_If applicable, add screenshots to help explain your problem._
<img width="1435" alt="image" src="https://github.com/Kernel360/E2E1-KernelEngine/assets/111513287/f9698234-15f5-49f9-a9ae-a49c70784fda"><br>

**Comment by anso33** [comment]
감사합니다. 해결했습니다!
