### ISSUE TITLE
[버그 제보] 검색 결과 창 확인 시 조회순 / 최신순 확인 & 검색 결과 창 

### ISSUE THREAD

**Issue by fingersdanny** [Kernel360/E2E1-KernelEngine#126]
> **Describe the bug**
_A clear and concise description of what the bug is._
 * 검색 결과 확인 시 조회 순 / 최신 순 확인이 가능하면 좋을 거 같아요.
 * 제 검색 결과가 검색 창에 남아있으면 좋을 것 같습니다.
<br>

>  **To Reproduce**
_Steps to reproduce the behavior_

<br>

> **Expected behavior**
_A clear and concise description of what you expected to happen._

<br>

> **Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://github.com/Kernel360/E2E1-KernelEngine/assets/54776553/3780837b-79ee-4a36-acbe-f75173c9d6f9)

<br>

> **Desktop 환경:**

<br>

> **Smartphone 환경 구성:**

<br>

> **Additional context**
_Add any other context about the problem here._
고생 많으셨습니다!

**Comment by anso33** [comment]
감사합니댜 해결했습니다!
